### ISSUE TITLE
Help to create a Macro that use defparsec

### ISSUE THREAD

**Issue by meox** [plataformatec/nimble_parsec#27]
I'm trying to write a super-parser, smthg like this:

```elixir
  defmacro named_parser(name, parser, tag) do
    defparsec(
      name,
      symbol
      |> map({:extract, []})
      |> ignore(spaces)
      |> optional(int_t |> tag(:tag))
      |> ignore(spaces)
      |> ignore(ascii_char([?:]))
      |> ignore(spaces1)
      |> concat(parser)
      |> tag(tag)
      |> map({:data_field_prettify, []})
    )
  end
```

but it doesn't works.
So I tried this:

```elixir
  defmacro named_parser(name, parser, tag) do
    quote do
      defparsec(
        unquote(name),
        symbol
        |> map({:extract, []})
        |> ignore(spaces)
        |> optional(int_t |> tag(:tag))
        |> ignore(spaces)
        |> ignore(ascii_char([?:]))
        |> ignore(spaces1)
        |> concat(unquote(parser))
        |> tag(unquote(tag))
        |> map({:data_field_prettify, []})
      )
    end
  end
```

but I get this error:

```
== Compilation error in file lib/rulec/rulec_parser.ex ==
** (CompileError) lib/rulec/rulec_parser.ex:456: undefined function symbol/0
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) expanding macro: Kernel.|>/2
```

Any suggestion?

**Comment by whatyouhide** [comment]
Where is `symbol` coming from? Is it defined outside the macro?

**Comment by josevalim** [comment]
Hi @meox! As @whatyouhide said, make sure that all variables are unquoted, otherwise you will get undefined function/variable errors.

**Comment by meox** [comment]
Ok, I've moved my code in the same module.
The problem now is a different

```elixir
defmodule RuleC.Macro do
  import NimbleParsec

  # some other stuff here

  defmacro named_parser(name, parser, tag) do
    quote do
      defparsec(
        unquote(name),
        symbol
        |> map({:extract, []})
        |> ignore(spaces)
        |> optional(int_t |> tag(:tag))
        |> ignore(spaces)
        |> ignore(ascii_char([?:]))
        |> ignore(spaces1)
        |> concat(unquote(parser))
        |> tag(unquote(tag))
        |> map({:data_field_prettify, []})
      )
    end
  end

  named_parser(
    :data_map_type,
    parsec(:data_anonymous_map_t),
    :tag_data_map_type
  )

end
```

I'm getting:

```
== Compilation error in file lib/rulec/rulec_parser.ex ==
** (CompileError) lib/rulec/rulec_parser.ex:472: undefined function named_parser/3
```

I semplified the problem with this stupid module:
```elixir
defmodule TestMacro do

  defmacro my_macro(x) do
    quote do
      unquote(x) + 1
    end
  end

  def my_fun() do
    my_macro(5)
  end
end
```

This works (as expected) but not this one:

```elixir
defmodule TestMacro do

  defmacro my_macro(x) do
    quote do
      unquote(x) + 1
    end
  end

  my_macro(5)
end
```

So seems that I have to define the macro in a different module. Is it right?

**Comment by josevalim** [comment]
Yes, exactly.

**Comment by meox** [comment]
In order to resolve this issue I found now another problem:
seems that is not possible to invoke a parser defined in onother module using parsec. 

I'm going to explain it better.
I have now 3 files:
- RuleC.Parser (that contains the main parser spec)
- RuleC.BasicDef (that contains only some basic definition of the language)
- RuleC.Macro (that contain 1 macro)

RuleC.BasicDef "import" NimbleParsec
RuleC.Macro "import" NimbleParsec and RuleC.BasicDef
RuleC.Parser "import" NimbleParsec, RuleC.BasicDef and  RuleC.Macro

Inside RuleC.Parser there are many defparsec that use parser defined in RuleC.BasicDef.
```
== Compilation error in file lib/rulec/rulec_parser.ex ==
** (CompileError) lib/rulec/rulec_parser.ex:17: undefined function spaces__0/6
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

Any suggestion?
